INFO 2022-05-06 11:10:31,931 autoreload 12956 14876 Watching for file changes with StatReloader
INFO 2022-05-06 11:10:53,623 basehttp 12956 14692 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-05-06 11:10:53,739 basehttp 12956 14692 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2022-05-06 11:10:53,883 basehttp 12956 14692 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-05-06 11:10:54,003 basehttp 12956 14692 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2022-05-06 11:11:03,568 basehttp 12956 14692 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2377
INFO 2022-05-06 11:11:16,292 basehttp 12956 14692 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2376
INFO 2022-05-06 11:14:12,839 autoreload 2420 13536 Watching for file changes with StatReloader
INFO 2022-05-06 11:14:54,430 basehttp 2420 7660 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2022-05-06 11:14:54,550 basehttp 2420 7660 "GET /admin/ HTTP/1.1" 200 5215
INFO 2022-05-06 11:15:05,291 basehttp 2420 7660 "GET /admin/myApp/issue/ HTTP/1.1" 200 5917
INFO 2022-05-06 11:15:05,403 basehttp 2420 7660 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:17:26,247 basehttp 2420 7660 "GET /admin/ HTTP/1.1" 200 5215
INFO 2022-05-06 11:19:03,674 autoreload 16672 16608 Watching for file changes with StatReloader
INFO 2022-05-06 11:21:05,421 basehttp 16672 13300 "GET /admin/myApp/comment/ HTTP/1.1" 302 0
INFO 2022-05-06 11:21:05,581 basehttp 16672 13300 "GET /admin/login/?next=/admin/myApp/comment/ HTTP/1.1" 200 2243
INFO 2022-05-06 11:21:12,873 basehttp 16672 13300 "POST /admin/login/?next=/admin/myApp/comment/ HTTP/1.1" 302 0
INFO 2022-05-06 11:21:12,945 basehttp 16672 13300 "GET /admin/myApp/comment/ HTTP/1.1" 200 5931
INFO 2022-05-06 11:21:13,049 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:21:31,912 basehttp 16672 13300 "GET /admin/myApp/user/ HTTP/1.1" 200 5910
INFO 2022-05-06 11:21:31,984 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:21:34,144 basehttp 16672 13300 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7548
INFO 2022-05-06 11:21:34,296 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:21:52,993 basehttp 16672 13300 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:21:53,169 basehttp 16672 13300 "GET /admin/myApp/user/ HTTP/1.1" 200 7242
INFO 2022-05-06 11:21:53,297 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:21:57,652 basehttp 16672 13300 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7548
INFO 2022-05-06 11:21:57,772 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:22:12,239 basehttp 16672 13300 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:22:12,375 basehttp 16672 13300 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7773
INFO 2022-05-06 11:22:12,495 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:22:34,288 basehttp 16672 13300 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:22:34,464 basehttp 16672 13300 "GET /admin/myApp/user/ HTTP/1.1" 200 7645
INFO 2022-05-06 11:22:34,560 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:22:42,494 basehttp 16672 13300 "GET /admin/myApp/project/ HTTP/1.1" 200 5931
INFO 2022-05-06 11:22:42,638 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:22:45,457 basehttp 16672 13300 "GET /admin/myApp/project/add/ HTTP/1.1" 200 8374
INFO 2022-05-06 11:22:45,569 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:22:59,275 basehttp 16672 13300 "POST /admin/myApp/project/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:22:59,435 basehttp 16672 13300 "GET /admin/myApp/project/add/ HTTP/1.1" 200 8608
INFO 2022-05-06 11:22:59,571 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:23:11,480 basehttp 16672 13300 "POST /admin/myApp/project/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:23:11,584 basehttp 16672 13300 "GET /admin/myApp/project/ HTTP/1.1" 200 7487
INFO 2022-05-06 11:23:11,752 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:23:13,407 basehttp 16672 13300 "GET /admin/myApp/issue/ HTTP/1.1" 200 5917
INFO 2022-05-06 11:23:13,519 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:23:16,586 basehttp 16672 13300 "GET /admin/myApp/issue/add/ HTTP/1.1" 200 11047
INFO 2022-05-06 11:23:16,690 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:23:38,825 basehttp 16672 13300 "POST /admin/myApp/issue/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:23:38,977 basehttp 16672 13300 "GET /admin/myApp/issue/add/ HTTP/1.1" 200 11283
INFO 2022-05-06 11:23:39,097 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:24:21,486 basehttp 16672 13300 "POST /admin/myApp/issue/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:24:21,566 basehttp 16672 13300 "GET /admin/myApp/issue/ HTTP/1.1" 200 7489
INFO 2022-05-06 11:24:21,670 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:24:24,889 basehttp 16672 13300 "GET /admin/myApp/comment/ HTTP/1.1" 200 5931
INFO 2022-05-06 11:24:24,985 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:24:27,187 basehttp 16672 13300 "GET /admin/myApp/comment/add/ HTTP/1.1" 200 10887
INFO 2022-05-06 11:24:27,299 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:24:59,490 basehttp 16672 13300 "POST /admin/myApp/comment/add/ HTTP/1.1" 200 11128
INFO 2022-05-06 11:24:59,594 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:25:05,119 basehttp 16672 13300 "POST /admin/myApp/comment/add/ HTTP/1.1" 302 0
INFO 2022-05-06 11:25:05,255 basehttp 16672 13300 "GET /admin/myApp/comment/ HTTP/1.1" 200 7278
INFO 2022-05-06 11:25:05,359 basehttp 16672 13300 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 11:28:02,889 autoreload 15788 8332 Watching for file changes with StatReloader
WARNING 2022-05-06 11:36:01,157 log 15788 16472 Method Not Allowed: /api/token/
WARNING 2022-05-06 11:36:01,157 basehttp 15788 16472 "GET /api/token/ HTTP/1.1" 405 40
INFO 2022-05-06 11:36:57,321 basehttp 15788 16472 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-06 11:37:46,542 basehttp 15788 16472 "GET /user/ HTTP/1.1" 200 237
INFO 2022-05-06 11:37:56,143 basehttp 15788 16472 "GET /issue/ HTTP/1.1" 200 340
WARNING 2022-05-06 11:38:08,951 log 15788 16472 Unauthorized: /issue/
WARNING 2022-05-06 11:38:08,951 basehttp 15788 16472 "GET /issue/ HTTP/1.1" 401 183
INFO 2022-05-06 11:38:16,755 basehttp 15788 16472 "GET /issue/ HTTP/1.1" 200 340
INFO 2022-05-06 12:33:44,773 autoreload 15788 8332 F:\ProjectHUE\myApp\models.py changed, reloading.
INFO 2022-05-06 12:33:46,380 autoreload 15764 16432 Watching for file changes with StatReloader
ERROR 2022-05-06 12:33:56,173 log 15764 15932 Internal Server Error: /admin/myApp/comment/
Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\utils.py", line 266, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\utils.py", line 297, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Comment has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\library.py", line 215, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in result_list
    'results': list(results(cl)),
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 285, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 276, in __init__
    super().__init__(*items)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 201, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\utils.py", line 279, in lookup_field
    value = attr()
  File "F:\ProjectHUE\myApp\models.py", line 48, in __str__
    return '%s - %s' % (self.author, self.Issue.issueName)
AttributeError: 'Comment' object has no attribute 'Issue'
ERROR 2022-05-06 12:33:56,178 basehttp 15764 15932 "GET /admin/myApp/comment/ HTTP/1.1" 500 381803
INFO 2022-05-06 12:34:10,464 autoreload 15764 16432 F:\ProjectHUE\myApp\models.py changed, reloading.
INFO 2022-05-06 12:34:12,072 autoreload 1824 3648 Watching for file changes with StatReloader
INFO 2022-05-06 12:34:22,047 basehttp 1824 14228 "GET /admin/myApp/comment/ HTTP/1.1" 200 7165
INFO 2022-05-06 12:34:22,174 basehttp 1824 14228 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:34:52,099 autoreload 1824 3648 F:\ProjectHUE\myApp\models.py changed, reloading.
INFO 2022-05-06 12:34:53,350 autoreload 15200 6748 Watching for file changes with StatReloader
INFO 2022-05-06 12:34:57,948 basehttp 15200 14632 "GET /admin/myApp/comment/ HTTP/1.1" 200 7096
INFO 2022-05-06 12:34:58,025 basehttp 15200 14632 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:35:44,176 autoreload 15200 6748 F:\ProjectHUE\myApp\models.py changed, reloading.
INFO 2022-05-06 12:35:45,339 autoreload 5548 13288 Watching for file changes with StatReloader
INFO 2022-05-06 12:35:51,201 basehttp 5548 3404 "GET /admin/myApp/comment/ HTTP/1.1" 200 7108
INFO 2022-05-06 12:35:51,276 basehttp 5548 3404 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:47:00,524 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 9353
INFO 2022-05-06 12:47:00,647 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:47:00,932 basehttp 5548 12792 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2022-05-06 12:47:44,530 basehttp 5548 12792 "GET /admin/auth/user/1/change/ HTTP/1.1" 200 17594
INFO 2022-05-06 12:47:44,653 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:47:44,675 basehttp 5548 16152 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
INFO 2022-05-06 12:47:44,694 basehttp 5548 472 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
INFO 2022-05-06 12:47:45,025 basehttp 5548 472 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2022-05-06 12:47:45,031 basehttp 5548 16152 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2022-05-06 12:47:45,033 basehttp 5548 12792 "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2022-05-06 12:47:58,817 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 9353
INFO 2022-05-06 12:48:09,574 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 9353
INFO 2022-05-06 12:48:09,681 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:48:22,814 basehttp 5548 12792 "GET /admin/auth/user/add/ HTTP/1.1" 200 8384
INFO 2022-05-06 12:48:22,907 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:48:45,052 basehttp 5548 12792 "POST /admin/auth/user/add/ HTTP/1.1" 200 8547
INFO 2022-05-06 12:48:45,162 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:49:01,578 basehttp 5548 12792 "POST /admin/auth/user/add/ HTTP/1.1" 200 8622
INFO 2022-05-06 12:49:01,662 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:49:19,337 basehttp 5548 12792 "POST /admin/auth/user/add/ HTTP/1.1" 200 8563
INFO 2022-05-06 12:49:19,447 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:49:47,909 basehttp 5548 12792 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2022-05-06 12:49:48,019 basehttp 5548 12792 "GET /admin/auth/user/add/ HTTP/1.1" 200 8608
INFO 2022-05-06 12:49:48,143 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:50:07,458 basehttp 5548 12792 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2022-05-06 12:50:07,548 basehttp 5548 12792 "GET /admin/auth/user/add/ HTTP/1.1" 200 8607
INFO 2022-05-06 12:50:07,656 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:50:18,623 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10121
INFO 2022-05-06 12:50:18,714 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:50:18,804 basehttp 5548 12792 "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2022-05-06 12:50:27,436 basehttp 5548 12792 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 17517
INFO 2022-05-06 12:50:27,554 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:50:48,930 basehttp 5548 12792 "GET /admin/auth/group/ HTTP/1.1" 200 6262
INFO 2022-05-06 12:50:49,007 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:50:51,973 basehttp 5548 12792 "GET /admin/auth/group/add/ HTTP/1.1" 200 10155
INFO 2022-05-06 12:50:52,087 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:51:38,426 basehttp 5548 12792 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2022-05-06 12:51:38,529 basehttp 5548 12792 "GET /admin/auth/group/add/ HTTP/1.1" 200 10381
INFO 2022-05-06 12:51:38,658 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:53:51,765 basehttp 5548 12792 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2022-05-06 12:53:51,852 basehttp 5548 12792 "GET /admin/auth/group/add/ HTTP/1.1" 200 10391
INFO 2022-05-06 12:53:51,957 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:54:56,975 basehttp 5548 12792 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2022-05-06 12:54:57,057 basehttp 5548 12792 "GET /admin/auth/group/ HTTP/1.1" 200 8008
INFO 2022-05-06 12:54:57,174 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:54:59,957 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10529
INFO 2022-05-06 12:55:00,044 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:03,980 basehttp 5548 12792 "GET /admin/auth/user/1/change/ HTTP/1.1" 200 17711
INFO 2022-05-06 12:55:04,088 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:20,298 basehttp 5548 12792 "POST /admin/auth/user/1/change/ HTTP/1.1" 302 0
INFO 2022-05-06 12:55:20,401 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10723
INFO 2022-05-06 12:55:20,510 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:23,055 basehttp 5548 12792 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 17634
INFO 2022-05-06 12:55:23,153 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:31,861 basehttp 5548 12792 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2022-05-06 12:55:31,951 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10723
INFO 2022-05-06 12:55:32,096 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:34,937 basehttp 5548 12792 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 17630
INFO 2022-05-06 12:55:35,030 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:45,472 basehttp 5548 12792 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2022-05-06 12:55:45,571 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10722
INFO 2022-05-06 12:55:45,657 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:55:55,718 basehttp 5548 12792 "GET /admin/logout/ HTTP/1.1" 200 1530
INFO 2022-05-06 12:55:57,968 basehttp 5548 12792 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-05-06 12:55:58,046 basehttp 5548 12792 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2022-05-06 12:56:09,720 basehttp 5548 12792 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2377
INFO 2022-05-06 12:56:17,894 basehttp 5548 12792 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2022-05-06 12:56:17,978 basehttp 5548 12792 "GET /admin/ HTTP/1.1" 200 8068
INFO 2022-05-06 12:56:26,525 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10529
INFO 2022-05-06 12:56:26,707 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:56:40,298 basehttp 5548 12792 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 17643
INFO 2022-05-06 12:56:40,409 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:57:31,388 basehttp 5548 12792 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2022-05-06 12:57:31,500 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10740
INFO 2022-05-06 12:57:31,607 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:57:34,452 basehttp 5548 12792 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 17639
INFO 2022-05-06 12:57:34,558 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:57:49,601 basehttp 5548 12792 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2022-05-06 12:57:49,700 basehttp 5548 12792 "GET /admin/auth/user/ HTTP/1.1" 200 10754
INFO 2022-05-06 12:57:49,830 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 12:58:31,644 basehttp 5548 4928 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-06 12:59:22,462 basehttp 5548 4928 "GET /user/ HTTP/1.1" 200 237
INFO 2022-05-06 12:59:58,401 basehttp 5548 4928 "GET /user/ HTTP/1.1" 200 237
INFO 2022-05-06 13:00:06,970 basehttp 5548 12792 "GET /admin/auth/group/ HTTP/1.1" 200 7816
INFO 2022-05-06 13:00:07,054 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 13:00:11,611 basehttp 5548 12792 "GET /admin/auth/group/3/change/ HTTP/1.1" 200 10456
INFO 2022-05-06 13:00:11,731 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 13:00:20,797 basehttp 5548 12792 "POST /admin/auth/group/3/change/ HTTP/1.1" 302 0
INFO 2022-05-06 13:00:20,894 basehttp 5548 12792 "GET /admin/auth/group/ HTTP/1.1" 200 8010
INFO 2022-05-06 13:00:21,018 basehttp 5548 12792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 13:00:31,322 basehttp 5548 4928 "GET /user/ HTTP/1.1" 200 237
INFO 2022-05-06 13:00:33,187 basehttp 5548 4928 "GET /user/ HTTP/1.1" 200 237
INFO 2022-05-06 13:00:53,922 basehttp 5548 12792 "GET /admin/logout/ HTTP/1.1" 200 1530
INFO 2022-05-06 13:00:56,472 basehttp 5548 12792 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-05-06 13:00:56,522 basehttp 5548 12792 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2022-05-06 13:01:10,200 basehttp 5548 12792 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2022-05-06 13:01:10,251 basehttp 5548 12792 "GET /admin/ HTTP/1.1" 200 3594
INFO 2022-05-06 13:01:10,502 basehttp 5548 12792 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2022-05-06 15:38:20,339 basehttp 5548 2420 "GET /admin/myApp/issue/ HTTP/1.1" 200 4970
INFO 2022-05-06 15:38:24,201 basehttp 5548 2420 "GET /admin/myApp/project/ HTTP/1.1" 200 4968
INFO 2022-05-06 15:38:27,133 basehttp 5548 2420 "GET /admin/myApp/project/1/change/ HTTP/1.1" 200 6148
INFO 2022-05-06 15:38:27,253 basehttp 5548 2420 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 15:38:30,531 basehttp 5548 2420 "GET /admin/myApp/issue/ HTTP/1.1" 200 4970
INFO 2022-05-06 15:38:32,113 basehttp 5548 2420 "GET /admin/myApp/issue/2/change/ HTTP/1.1" 200 7801
INFO 2022-05-06 15:38:32,241 basehttp 5548 2420 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-06 16:25:42,198 autoreload 17268 7964 Watching for file changes with StatReloader
INFO 2022-05-06 16:26:08,363 basehttp 17268 1140 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-06 16:26:36,242 basehttp 17268 1140 "GET /user/ HTTP/1.1" 200 237
ERROR 2022-05-06 16:29:32,730 log 17268 1140 Internal Server Error: /issue/
Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\ProjectHUE\api\views.py", line 48, in post
    email.send()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor g12-20020ac842cc000000b002f39b99f678sm2388744qtm.18 - gsmtp')
ERROR 2022-05-06 16:29:32,738 basehttp 17268 1140 "POST /issue/ HTTP/1.1" 500 119293
INFO 2022-05-06 16:29:51,067 basehttp 17268 10484 "GET /admin/myApp/issue/ HTTP/1.1" 200 4970
INFO 2022-05-06 16:33:01,618 autoreload 17300 11336 Watching for file changes with StatReloader
WARNING 2022-05-06 16:33:18,041 log 17300 10908 Bad Request: /api/token/
WARNING 2022-05-06 16:33:18,041 basehttp 17300 10908 "POST /api/token/ HTTP/1.1" 400 79
INFO 2022-05-06 16:33:59,695 basehttp 17300 13904 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-06 16:34:18,952 basehttp 17300 12388 "GET /user/ HTTP/1.1" 200 237
ERROR 2022-05-06 16:35:17,676 log 17300 11196 Internal Server Error: /issue/
Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\ProjectHUE\api\views.py", line 48, in post
    email.send()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor cz7-20020a0564021ca700b0042617ba63cfsm2113521edb.89 - gsmtp')
ERROR 2022-05-06 16:35:17,676 basehttp 17300 11196 "POST /issue/ HTTP/1.1" 500 119173
INFO 2022-05-06 16:35:36,770 basehttp 17300 15136 "GET /admin/myApp/issue/ HTTP/1.1" 200 4970
INFO 2022-05-06 16:40:03,710 autoreload 17300 11336 F:\ProjectHUE\api\views.py changed, reloading.
INFO 2022-05-06 16:40:05,325 autoreload 15464 4928 Watching for file changes with StatReloader
INFO 2022-05-06 16:40:12,107 autoreload 15464 4928 F:\ProjectHUE\api\views.py changed, reloading.
INFO 2022-05-06 16:40:14,060 autoreload 13564 2864 Watching for file changes with StatReloader
WARNING 2022-05-06 16:40:30,524 log 13564 7920 Unauthorized: /issue/
WARNING 2022-05-06 16:40:30,524 basehttp 13564 7920 "POST /issue/ HTTP/1.1" 401 183
INFO 2022-05-06 16:41:02,183 basehttp 13564 6236 "POST /api/token/ HTTP/1.1" 200 483
ERROR 2022-05-06 16:41:18,943 log 13564 15436 Internal Server Error: /issue/
Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\ProjectHUE\api\views.py", line 41, in post
    send_mail(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 61, in send_mail
    return mail.send()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor el22-20020a170907285600b006f3ef214e32sm1822505ejc.152 - gsmtp')
ERROR 2022-05-06 16:41:18,951 basehttp 13564 15436 "POST /issue/ HTTP/1.1" 500 124267
ERROR 2022-05-06 16:44:52,867 log 13564 16980 Internal Server Error: /issue/
Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\ProjectHUE\api\views.py", line 41, in post
    send_mail(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\__init__.py", line 61, in send_mail
    return mail.send()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d5-20020a170906304500b006f3ef214e05sm1813474ejd.107 - gsmtp')
ERROR 2022-05-06 16:44:52,867 basehttp 13564 16980 "POST /issue/ HTTP/1.1" 500 124249
INFO 2022-05-06 16:50:30,336 autoreload 13564 2864 F:\ProjectHUE\api\views.py changed, reloading.
INFO 2022-05-06 16:50:32,291 autoreload 2924 1444 Watching for file changes with StatReloader
INFO 2022-05-06 16:50:39,680 basehttp 2924 16632 "POST /api/token/ HTTP/1.1" 200 483
ERROR 2022-05-06 16:50:59,892 log 2924 14176 Internal Server Error: /issue/
Traceback (most recent call last):
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\ProjectHUE\api\views.py", line 48, in post
    email.send()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\rashi\AppData\Local\Programs\Python\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor ht7-20020a170907608700b006f3ef214dc7sm1861105ejc.45 - gsmtp')
ERROR 2022-05-06 16:50:59,892 basehttp 2924 14176 "POST /issue/ HTTP/1.1" 500 119173
INFO 2022-05-06 16:55:42,938 autoreload 2924 1444 F:\ProjectHUE\LY3000\settings.py changed, reloading.
INFO 2022-05-06 16:55:45,040 autoreload 15792 12956 Watching for file changes with StatReloader
WARNING 2022-05-06 16:55:52,364 log 15792 6092 Unauthorized: /issue/
WARNING 2022-05-06 16:55:52,364 basehttp 15792 6092 "POST /issue/ HTTP/1.1" 401 183
INFO 2022-05-06 16:55:56,609 basehttp 15792 8160 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-06 16:56:15,449 basehttp 15792 9832 "POST /issue/ HTTP/1.1" 200 178
INFO 2022-05-06 16:59:14,960 basehttp 15792 14192 "GET /admin/myApp/issue/ HTTP/1.1" 200 5077
INFO 2022-05-06 17:05:38,309 autoreload 15792 12956 F:\ProjectHUE\LY3000\settings.py changed, reloading.
INFO 2022-05-06 17:05:39,908 autoreload 8196 5256 Watching for file changes with StatReloader
INFO 2022-05-06 17:18:46,549 autoreload 8196 5256 F:\ProjectHUE\LY3000\settings.py changed, reloading.
INFO 2022-05-06 14:51:34,503 autoreload 18906 4364748160 Watching for file changes with StatReloader
INFO 2022-05-08 06:05:10,473 autoreload 19044 4366697856 Watching for file changes with StatReloader
WARNING 2022-05-08 06:05:21,483 log 19044 6136459264 Not Found: /
WARNING 2022-05-08 06:05:21,483 basehttp 19044 6136459264 "GET / HTTP/1.1" 404 3044
WARNING 2022-05-08 06:05:21,639 log 19044 6136459264 Not Found: /favicon.ico
WARNING 2022-05-08 06:05:21,639 basehttp 19044 6136459264 "GET /favicon.ico HTTP/1.1" 404 3095
INFO 2022-05-08 06:05:29,145 basehttp 19044 6136459264 "GET /admin HTTP/1.1" 301 0
INFO 2022-05-08 06:05:29,173 basehttp 19044 6136459264 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-05-08 06:05:29,204 basehttp 19044 6136459264 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2215
INFO 2022-05-08 06:05:29,237 basehttp 19044 6170112000 "GET /static/admin/css/login.css HTTP/1.1" 200 954
INFO 2022-05-08 06:05:29,237 basehttp 19044 6153285632 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616
INFO 2022-05-08 06:05:29,238 basehttp 19044 6136459264 "GET /static/admin/css/base.css HTTP/1.1" 200 19513
INFO 2022-05-08 06:05:29,238 basehttp 19044 6186938368 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18575
INFO 2022-05-08 06:05:29,243 basehttp 19044 6186938368 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401
INFO 2022-05-08 06:05:29,251 basehttp 19044 6186938368 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2022-05-08 06:05:29,270 basehttp 19044 6186938368 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2022-05-08 06:05:29,270 basehttp 19044 6170112000 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
INFO 2022-05-08 06:05:36,649 basehttp 19044 6170112000 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2377
INFO 2022-05-08 06:05:36,696 basehttp 19044 6170112000 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
INFO 2022-05-08 06:08:22,063 autoreload 20117 4380558720 Watching for file changes with StatReloader
INFO 2022-05-08 06:08:31,817 basehttp 20117 6124105728 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2022-05-08 06:08:31,860 basehttp 20117 6124105728 "GET /admin/ HTTP/1.1" 200 5215
INFO 2022-05-08 06:08:31,875 basehttp 20117 6124105728 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
INFO 2022-05-08 06:08:31,914 basehttp 20117 6140932096 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2022-05-08 06:08:31,915 basehttp 20117 6124105728 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2022-05-08 06:08:45,422 basehttp 20117 6124105728 "GET /admin/auth/group/ HTTP/1.1" 200 6262
INFO 2022-05-08 06:08:45,455 basehttp 20117 6124105728 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6932
INFO 2022-05-08 06:08:45,457 basehttp 20117 6174584832 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2022-05-08 06:08:45,458 basehttp 20117 6124105728 "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
INFO 2022-05-08 06:08:45,458 basehttp 20117 6191411200 "GET /static/admin/js/core.js HTTP/1.1" 200 5698
INFO 2022-05-08 06:08:45,459 basehttp 20117 6208237568 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
INFO 2022-05-08 06:08:45,460 basehttp 20117 6124105728 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2022-05-08 06:08:45,461 basehttp 20117 6174584832 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
INFO 2022-05-08 06:08:45,463 basehttp 20117 6157758464 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
INFO 2022-05-08 06:08:45,463 basehttp 20117 6191411200 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
INFO 2022-05-08 06:08:45,475 basehttp 20117 6191411200 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2022-05-08 06:08:45,477 basehttp 20117 6140932096 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:08:45,496 basehttp 20117 6140932096 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2022-05-08 06:08:49,792 basehttp 20117 6140932096 "GET /admin/auth/group/add/ HTTP/1.1" 200 10155
INFO 2022-05-08 06:08:49,821 basehttp 20117 6124105728 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
INFO 2022-05-08 06:08:49,821 basehttp 20117 6140932096 "GET /static/admin/css/forms.css HTTP/1.1" 200 8878
INFO 2022-05-08 06:08:49,822 basehttp 20117 6157758464 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
INFO 2022-05-08 06:08:49,822 basehttp 20117 6174584832 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
INFO 2022-05-08 06:08:49,843 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:08:49,846 basehttp 20117 6191411200 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
INFO 2022-05-08 06:08:49,857 basehttp 20117 6191411200 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2022-05-08 06:08:49,884 basehttp 20117 6191411200 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2022-05-08 06:08:49,884 basehttp 20117 6174584832 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2022-05-08 06:08:49,884 basehttp 20117 6124105728 "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2022-05-08 06:09:06,548 basehttp 20117 6124105728 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:09:06,620 basehttp 20117 6124105728 "GET /admin/auth/group/ HTTP/1.1" 200 7595
INFO 2022-05-08 06:09:06,666 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:09:06,695 basehttp 20117 6124105728 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2022-05-08 06:09:12,812 basehttp 20117 6124105728 "GET /admin/auth/group/add/ HTTP/1.1" 200 10155
INFO 2022-05-08 06:09:12,846 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:11:07,285 basehttp 20117 6124105728 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:11:07,352 basehttp 20117 6124105728 "GET /admin/auth/group/ HTTP/1.1" 200 7818
INFO 2022-05-08 06:11:07,400 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:11:09,372 basehttp 20117 6124105728 "GET /admin/auth/group/add/ HTTP/1.1" 200 10155
INFO 2022-05-08 06:11:09,411 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:07,783 basehttp 20117 6124105728 "POST /admin/auth/group/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:12:07,834 basehttp 20117 6124105728 "GET /admin/auth/group/ HTTP/1.1" 200 8010
INFO 2022-05-08 06:12:07,874 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:11,923 basehttp 20117 6124105728 "GET /admin/auth/user/add/ HTTP/1.1" 200 8384
INFO 2022-05-08 06:12:11,968 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:19,471 basehttp 20117 6124105728 "GET /admin/myApp/user/ HTTP/1.1" 200 5910
INFO 2022-05-08 06:12:19,512 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:21,607 basehttp 20117 6124105728 "GET /admin/auth/user/ HTTP/1.1" 200 9763
INFO 2022-05-08 06:12:21,645 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:21,668 basehttp 20117 6124105728 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2022-05-08 06:12:28,668 basehttp 20117 6124105728 "GET /admin/auth/user/1/change/ HTTP/1.1" 200 17712
INFO 2022-05-08 06:12:28,684 basehttp 20117 6174584832 "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
INFO 2022-05-08 06:12:28,684 basehttp 20117 6191411200 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
INFO 2022-05-08 06:12:28,706 basehttp 20117 6124105728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:28,738 basehttp 20117 6191411200 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2022-05-08 06:12:28,738 basehttp 20117 6124105728 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2022-05-08 06:12:38,780 basehttp 20117 6191411200 "POST /admin/auth/user/1/change/ HTTP/1.1" 302 0
INFO 2022-05-08 06:12:38,868 basehttp 20117 6191411200 "GET /admin/auth/user/ HTTP/1.1" 200 9957
INFO 2022-05-08 06:12:38,910 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:12:44,172 basehttp 20117 6191411200 "GET /admin/auth/user/add/ HTTP/1.1" 200 8384
INFO 2022-05-08 06:12:44,212 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:13:02,439 basehttp 20117 6191411200 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:13:02,478 basehttp 20117 6191411200 "GET /admin/auth/user/add/ HTTP/1.1" 200 8608
INFO 2022-05-08 06:13:02,512 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:13:29,573 basehttp 20117 6191411200 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:13:29,618 basehttp 20117 6191411200 "GET /admin/auth/user/add/ HTTP/1.1" 200 8607
INFO 2022-05-08 06:13:29,655 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:13:34,405 basehttp 20117 6191411200 "GET /admin/auth/user/ HTTP/1.1" 200 10531
INFO 2022-05-08 06:13:34,447 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:13:34,449 basehttp 20117 6191411200 "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2022-05-08 06:13:40,169 basehttp 20117 6191411200 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 17631
INFO 2022-05-08 06:13:40,214 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:13:54,966 basehttp 20117 6191411200 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2022-05-08 06:13:55,049 basehttp 20117 6191411200 "GET /admin/auth/user/ HTTP/1.1" 200 10724
INFO 2022-05-08 06:13:55,098 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:13:56,798 basehttp 20117 6191411200 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 17635
INFO 2022-05-08 06:13:56,839 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:14:14,885 basehttp 20117 6191411200 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2022-05-08 06:14:14,962 basehttp 20117 6191411200 "GET /admin/auth/user/ HTTP/1.1" 200 10741
INFO 2022-05-08 06:14:15,011 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:14:16,922 basehttp 20117 6191411200 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 17648
INFO 2022-05-08 06:14:16,963 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:14:32,346 basehttp 20117 6191411200 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2022-05-08 06:14:32,434 basehttp 20117 6191411200 "GET /admin/auth/user/ HTTP/1.1" 200 10755
INFO 2022-05-08 06:14:32,486 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:14:41,928 basehttp 20117 6191411200 "GET /admin/myApp/user/ HTTP/1.1" 200 5910
INFO 2022-05-08 06:14:41,969 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:14:44,023 basehttp 20117 6191411200 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7548
INFO 2022-05-08 06:14:44,062 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:15:04,947 basehttp 20117 6191411200 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:15:05,021 basehttp 20117 6191411200 "GET /admin/myApp/user/ HTTP/1.1" 200 7242
INFO 2022-05-08 06:15:05,073 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:15:08,329 basehttp 20117 6191411200 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7548
INFO 2022-05-08 06:15:08,376 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:15:27,848 basehttp 20117 6191411200 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:15:27,916 basehttp 20117 6191411200 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7771
INFO 2022-05-08 06:15:27,959 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:15:37,845 basehttp 20117 6191411200 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:15:37,908 basehttp 20117 6191411200 "GET /admin/myApp/user/add/ HTTP/1.1" 200 7772
INFO 2022-05-08 06:15:37,944 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:15:52,640 basehttp 20117 6191411200 "POST /admin/myApp/user/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:15:52,714 basehttp 20117 6191411200 "GET /admin/myApp/user/ HTTP/1.1" 200 7849
INFO 2022-05-08 06:15:52,761 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:15:58,295 basehttp 20117 6191411200 "GET /admin/myApp/project/ HTTP/1.1" 200 5931
INFO 2022-05-08 06:15:58,324 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:16:00,202 basehttp 20117 6191411200 "GET /admin/myApp/project/add/ HTTP/1.1" 200 8410
INFO 2022-05-08 06:16:00,245 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:16:45,985 basehttp 20117 6191411200 "POST /admin/myApp/project/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:16:46,059 basehttp 20117 6191411200 "GET /admin/myApp/project/add/ HTTP/1.1" 200 8650
INFO 2022-05-08 06:16:46,111 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:17:18,150 basehttp 20117 6191411200 "POST /admin/myApp/project/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:17:18,232 basehttp 20117 6191411200 "GET /admin/myApp/project/ HTTP/1.1" 200 7491
INFO 2022-05-08 06:17:18,280 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:17:19,812 basehttp 20117 6191411200 "GET /admin/myApp/issue/ HTTP/1.1" 200 5917
INFO 2022-05-08 06:17:19,857 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:17:21,934 basehttp 20117 6191411200 "GET /admin/myApp/issue/add/ HTTP/1.1" 200 11088
INFO 2022-05-08 06:17:21,974 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:20:14,213 basehttp 20117 6191411200 "POST /admin/myApp/issue/add/ HTTP/1.1" 302 0
INFO 2022-05-08 06:20:14,293 basehttp 20117 6191411200 "GET /admin/myApp/issue/ HTTP/1.1" 200 7272
INFO 2022-05-08 06:20:14,333 basehttp 20117 6191411200 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 06:30:30,820 basehttp 20117 6124105728 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-08 06:32:11,307 basehttp 20117 6124105728 "POST /issue/ HTTP/1.1" 200 178
INFO 2022-05-08 07:05:53,373 autoreload 37688 4365682048 Watching for file changes with StatReloader
INFO 2022-05-08 07:08:06,538 autoreload 37688 4365682048 /Users/rashussain/Desktop/Project/LY3000/settings.py changed, reloading.
INFO 2022-05-08 07:08:06,847 autoreload 38374 4344186240 Watching for file changes with StatReloader
INFO 2022-05-08 07:10:02,316 autoreload 39014 4369565056 Watching for file changes with StatReloader
INFO 2022-05-08 07:10:18,515 basehttp 39014 6132543488 "GET /admin/myApp/issue/ HTTP/1.1" 200 7288
INFO 2022-05-08 07:10:18,558 basehttp 39014 6132543488 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 07:10:22,502 basehttp 39014 6132543488 "GET /admin/myApp/comment/ HTTP/1.1" 200 5931
INFO 2022-05-08 07:10:22,540 basehttp 39014 6132543488 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 07:10:24,811 basehttp 39014 6132543488 "GET /admin/myApp/comment/add/ HTTP/1.1" 200 10928
INFO 2022-05-08 07:10:24,850 basehttp 39014 6132543488 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 07:10:51,706 basehttp 39014 6132543488 "GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
INFO 2022-05-08 07:10:59,769 basehttp 39014 6132543488 "POST /admin/myApp/comment/add/ HTTP/1.1" 302 0
INFO 2022-05-08 07:10:59,853 basehttp 39014 6132543488 "GET /admin/myApp/comment/ HTTP/1.1" 200 7338
INFO 2022-05-08 07:10:59,900 basehttp 39014 6132543488 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 07:59:47,083 autoreload 39014 4369565056 /Users/rashussain/Desktop/Project/LY3000/settings.py changed, reloading.
INFO 2022-05-08 07:59:47,464 autoreload 53778 4334126464 Watching for file changes with StatReloader
INFO 2022-05-08 08:00:51,659 autoreload 54146 4341319040 Watching for file changes with StatReloader
INFO 2022-05-08 13:28:04,783 autoreload 68378 4347872640 Watching for file changes with StatReloader
INFO 2022-05-08 13:28:14,797 basehttp 68378 6155939840 "POST /api/token/ HTTP/1.1" 200 483
ERROR 2022-05-08 13:29:09,995 log 68378 6155939840 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:29:09,996 basehttp 68378 6155939840 "PUT /issue/ HTTP/1.1" 500 90070
ERROR 2022-05-08 13:29:36,782 log 68378 6155939840 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:29:36,783 basehttp 68378 6155939840 "PUT /issue/ HTTP/1.1" 500 89559
INFO 2022-05-08 13:31:27,949 autoreload 68378 4347872640 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 13:31:28,325 autoreload 69403 4344874368 Watching for file changes with StatReloader
INFO 2022-05-08 13:31:38,350 basehttp 69403 6157234176 "GET /admin/myApp/issue/ HTTP/1.1" 200 7288
INFO 2022-05-08 13:31:38,374 basehttp 69403 6174060544 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,374 basehttp 69403 6190886912 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,376 basehttp 69403 6224539648 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,376 basehttp 69403 6174060544 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,376 basehttp 69403 6190886912 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,377 basehttp 69403 6207713280 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,377 basehttp 69403 6241366016 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,379 basehttp 69403 6241366016 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,380 basehttp 69403 6207713280 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,380 basehttp 69403 6224539648 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,380 basehttp 69403 6174060544 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,381 basehttp 69403 6190886912 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,396 basehttp 69403 6157234176 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 13:31:38,402 basehttp 69403 6157234176 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,412 basehttp 69403 6157234176 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,432 basehttp 69403 6157234176 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,432 basehttp 69403 6190886912 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,432 basehttp 69403 6207713280 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,432 basehttp 69403 6241366016 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2022-05-08 13:31:38,432 basehttp 69403 6174060544 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2022-05-08 13:31:43,516 basehttp 69403 6207713280 "GET /admin/myApp/issue/2/change/ HTTP/1.1" 200 11466
INFO 2022-05-08 13:31:43,530 basehttp 69403 6174060544 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:43,547 basehttp 69403 6174060544 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:43,547 basehttp 69403 6241366016 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2022-05-08 13:31:43,550 basehttp 69403 6207713280 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 13:31:43,554 basehttp 69403 6207713280 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2022-05-08 13:31:43,557 basehttp 69403 6207713280 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2022-05-08 13:31:46,711 basehttp 69403 6207713280 "GET /admin/myApp/issue/ HTTP/1.1" 200 7288
ERROR 2022-05-08 13:31:55,498 log 69403 6258192384 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:31:55,499 basehttp 69403 6258192384 "PUT /issue/ HTTP/1.1" 500 89558
ERROR 2022-05-08 13:32:33,500 log 69403 6258192384 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:32:33,501 basehttp 69403 6258192384 "PUT /issue/ HTTP/1.1" 500 90069
ERROR 2022-05-08 13:32:34,542 log 69403 6258192384 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:32:34,543 basehttp 69403 6258192384 "PUT /issue/ HTTP/1.1" 500 90069
ERROR 2022-05-08 13:32:35,447 log 69403 6258192384 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:32:35,447 basehttp 69403 6258192384 "PUT /issue/ HTTP/1.1" 500 90069
ERROR 2022-05-08 13:32:35,659 log 69403 6258192384 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:32:35,660 basehttp 69403 6258192384 "PUT /issue/ HTTP/1.1" 500 90069
ERROR 2022-05-08 13:32:35,871 log 69403 6258192384 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 57, in put
    serializer.save()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/serializers.py", line 180, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
ERROR 2022-05-08 13:32:35,872 basehttp 69403 6258192384 "PUT /issue/ HTTP/1.1" 500 90069
INFO 2022-05-08 13:32:41,951 basehttp 69403 6258192384 "GET /issue/ HTTP/1.1" 200 347
INFO 2022-05-08 13:38:08,172 autoreload 69403 4344874368 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 13:38:08,527 autoreload 71408 4373546368 Watching for file changes with StatReloader
WARNING 2022-05-08 13:38:59,646 log 71408 6128578560 Unauthorized: /issue/
WARNING 2022-05-08 13:38:59,646 basehttp 71408 6128578560 "PUT /issue/ HTTP/1.1" 401 183
INFO 2022-05-08 13:39:06,730 basehttp 71408 6128578560 "POST /api/token/ HTTP/1.1" 200 483
ERROR 2022-05-08 13:39:27,763 log 71408 6128578560 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/fields/__init__.py", line 1988, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'IssueView'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 55, in put
    issueObj= Issue.objects.get(issueId=issueId)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/sql/query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/sql/query.py", line 1273, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/fields/__init__.py", line 1990, in get_prep_value
    raise e.__class__(
TypeError: Field 'issueId' expected a number but got <api.views.IssueView object at 0x108066e90>.
ERROR 2022-05-08 13:39:27,764 basehttp 71408 6128578560 "PUT /issue/ HTTP/1.1" 500 143400
INFO 2022-05-08 13:46:50,717 autoreload 71408 4373546368 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 13:46:51,097 autoreload 74002 4378297728 Watching for file changes with StatReloader
WARNING 2022-05-08 13:46:59,466 log 74002 6126137344 Unauthorized: /issue/
WARNING 2022-05-08 13:46:59,466 basehttp 74002 6126137344 "PUT /issue/ HTTP/1.1" 401 183
INFO 2022-05-08 13:47:04,898 basehttp 74002 6126137344 "POST /api/token/ HTTP/1.1" 200 483
ERROR 2022-05-08 13:47:26,748 log 74002 6126137344 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: IssueView.put() missing 1 required positional argument: 'id'
ERROR 2022-05-08 13:47:26,749 basehttp 74002 6126137344 "PUT /issue/ HTTP/1.1" 500 80629
INFO 2022-05-08 13:52:07,111 autoreload 74002 4378297728 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 13:52:07,389 autoreload 75555 4299457920 Watching for file changes with StatReloader
WARNING 2022-05-08 13:52:17,720 log 75555 6205419520 Unauthorized: /issue/
WARNING 2022-05-08 13:52:17,720 basehttp 75555 6205419520 "PUT /issue/ HTTP/1.1" 401 183
INFO 2022-05-08 13:52:26,920 basehttp 75555 6205419520 "POST /api/token/ HTTP/1.1" 200 483
ERROR 2022-05-08 13:52:53,718 log 75555 6205419520 Internal Server Error: /issue/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: IssueView.put() missing 1 required positional argument: 'issueId'
ERROR 2022-05-08 13:52:53,718 basehttp 75555 6205419520 "PUT /issue/ HTTP/1.1" 500 80659
INFO 2022-05-08 13:55:14,673 autoreload 75555 4299457920 /Users/rashussain/Desktop/Project/api/urls.py changed, reloading.
INFO 2022-05-08 13:55:15,004 autoreload 76542 4302931328 Watching for file changes with StatReloader
ERROR 2022-05-08 13:55:24,584 log 76542 6199226368 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:55:24,584 basehttp 76542 6199226368 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:55:25,638 log 76542 6199226368 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:55:25,638 basehttp 76542 6199226368 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:55:25,769 log 76542 6199226368 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:55:25,769 basehttp 76542 6199226368 "PUT /issue/2 HTTP/1.1" 500 63938
INFO 2022-05-08 13:55:34,065 autoreload 76542 4302931328 /Users/rashussain/Desktop/Project/api/urls.py changed, reloading.
INFO 2022-05-08 13:55:34,352 autoreload 76653 4368827776 Watching for file changes with StatReloader
INFO 2022-05-08 13:56:19,548 autoreload 76653 4368827776 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 13:56:19,829 autoreload 76887 4341761408 Watching for file changes with StatReloader
ERROR 2022-05-08 13:56:23,981 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:23,981 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:56:24,618 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:24,618 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:56:24,797 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:24,798 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:56:24,962 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:24,963 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:56:25,112 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:25,112 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:56:25,244 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:25,244 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
ERROR 2022-05-08 13:56:25,398 log 76887 6159822848 Internal Server Error: /issue/2
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/issue/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-05-08 13:56:25,398 basehttp 76887 6159822848 "PUT /issue/2 HTTP/1.1" 500 63938
INFO 2022-05-08 13:56:34,181 basehttp 76887 6159822848 "GET /issue/2 HTTP/1.1" 301 0
ERROR 2022-05-08 13:56:34,231 log 76887 6159822848 Internal Server Error: /issue/2/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: IssueView.get() got an unexpected keyword argument 'issueId'
ERROR 2022-05-08 13:56:34,231 basehttp 76887 6159822848 "GET /issue/2/ HTTP/1.1" 500 80791
INFO 2022-05-08 13:56:34,807 basehttp 76887 6159822848 "GET /issue/2 HTTP/1.1" 301 0
ERROR 2022-05-08 13:56:34,847 log 76887 6159822848 Internal Server Error: /issue/2/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: IssueView.get() got an unexpected keyword argument 'issueId'
ERROR 2022-05-08 13:56:34,847 basehttp 76887 6159822848 "GET /issue/2/ HTTP/1.1" 500 80791
INFO 2022-05-08 13:56:35,034 basehttp 76887 6159822848 "GET /issue/2 HTTP/1.1" 301 0
ERROR 2022-05-08 13:56:35,074 log 76887 6159822848 Internal Server Error: /issue/2/
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: IssueView.get() got an unexpected keyword argument 'issueId'
ERROR 2022-05-08 13:56:35,075 basehttp 76887 6159822848 "GET /issue/2/ HTTP/1.1" 500 80791
INFO 2022-05-08 13:56:39,720 basehttp 76887 6159822848 "GET /issue/ HTTP/1.1" 200 347
WARNING 2022-05-08 13:56:58,655 log 76887 6159822848 Not Found: /issue/issueId:2
WARNING 2022-05-08 13:56:58,655 basehttp 76887 6159822848 "PUT /issue/issueId:2 HTTP/1.1" 404 3280
WARNING 2022-05-08 13:57:01,938 log 76887 6159822848 Not Found: /issue/issueId:2
WARNING 2022-05-08 13:57:01,938 basehttp 76887 6159822848 "PUT /issue/issueId:2 HTTP/1.1" 404 3280
WARNING 2022-05-08 13:57:09,243 log 76887 6159822848 Not Found: /issue/issueId=2
WARNING 2022-05-08 13:57:09,243 basehttp 76887 6159822848 "PUT /issue/issueId=2 HTTP/1.1" 404 3282
WARNING 2022-05-08 13:57:15,728 log 76887 6159822848 Not Found: /issue/issueId=2
WARNING 2022-05-08 13:57:15,728 basehttp 76887 6159822848 "PUT /issue/issueId=2 HTTP/1.1" 404 3282
INFO 2022-05-08 14:56:11,465 basehttp 76887 6159822848 "GET /admin/myApp/issue/2/change/ HTTP/1.1" 200 11466
INFO 2022-05-08 14:56:11,503 basehttp 76887 6159822848 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 14:56:20,163 basehttp 76887 6159822848 "GET /admin/myApp/issue/ HTTP/1.1" 200 7288
INFO 2022-05-08 14:57:05,969 autoreload 76887 4341761408 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 14:57:06,340 autoreload 90466 4301571456 Watching for file changes with StatReloader
INFO 2022-05-08 14:59:44,326 autoreload 90466 4301571456 /Users/rashussain/Desktop/Project/api/urls.py changed, reloading.
INFO 2022-05-08 14:59:44,623 autoreload 91258 4376757632 Watching for file changes with StatReloader
WARNING 2022-05-08 14:59:56,565 log 91258 6125219840 Unauthorized: /issue/2
WARNING 2022-05-08 14:59:56,566 basehttp 91258 6125219840 "PUT /issue/2 HTTP/1.1" 401 183
INFO 2022-05-08 15:00:01,415 basehttp 91258 6125219840 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-08 15:00:18,685 basehttp 91258 6125219840 "PUT /issue/2 HTTP/1.1" 200 176
INFO 2022-05-08 15:00:36,634 basehttp 91258 6125219840 "GET /admin/myApp/issue/2/change/ HTTP/1.1" 200 11464
INFO 2022-05-08 15:00:36,683 basehttp 91258 6125219840 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 15:00:41,425 basehttp 91258 6125219840 "GET /admin/myApp/issue/ HTTP/1.1" 200 7288
INFO 2022-05-08 15:01:26,227 basehttp 91258 6158872576 "PUT /issue/2 HTTP/1.1" 200 16
INFO 2022-05-08 15:02:03,058 basehttp 91258 6158872576 "PUT /issue/2 HTTP/1.1" 200 189
INFO 2022-05-08 15:06:36,989 autoreload 91258 4376757632 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 15:06:37,259 autoreload 93284 4304438656 Watching for file changes with StatReloader
WARNING 2022-05-08 15:06:55,542 log 93284 6200750080 Unauthorized: /issue/2
WARNING 2022-05-08 15:06:55,542 basehttp 93284 6200750080 "DELETE /issue/2 HTTP/1.1" 401 183
INFO 2022-05-08 15:07:00,890 basehttp 93284 6200750080 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-08 15:07:15,150 basehttp 93284 6200750080 "DELETE /issue/2 HTTP/1.1" 200 15
INFO 2022-05-08 15:07:34,410 basehttp 93284 6200750080 "GET /admin/myApp/issue/ HTTP/1.1" 200 7068
INFO 2022-05-08 15:07:34,448 basehttp 93284 6200750080 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 15:08:33,895 basehttp 93284 6234402816 "GET /issue/ HTTP/1.1" 200 168
INFO 2022-05-08 15:09:10,310 basehttp 93284 6217576448 "POST /issue/ HTTP/1.1" 200 175
INFO 2022-05-08 15:11:49,833 autoreload 93284 4304438656 /Users/rashussain/Desktop/Project/api/urls.py changed, reloading.
INFO 2022-05-08 15:11:50,140 autoreload 94883 4345759104 Watching for file changes with StatReloader
INFO 2022-05-08 15:11:56,906 basehttp 94883 6158102528 "GET /issues/ HTTP/1.1" 200 344
WARNING 2022-05-08 15:12:10,245 log 94883 6158102528 Unauthorized: /issues/2
WARNING 2022-05-08 15:12:10,245 basehttp 94883 6158102528 "GET /issues/2 HTTP/1.1" 401 183
WARNING 2022-05-08 15:12:13,728 log 94883 6158102528 Unauthorized: /issues/2
WARNING 2022-05-08 15:12:13,728 basehttp 94883 6158102528 "GET /issues/2 HTTP/1.1" 401 183
INFO 2022-05-08 15:20:59,004 autoreload 94883 4345759104 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 15:20:59,288 autoreload 97618 4333766016 Watching for file changes with StatReloader
INFO 2022-05-08 15:22:04,259 autoreload 97618 4333766016 /Users/rashussain/Desktop/Project/api/urls.py changed, reloading.
INFO 2022-05-08 15:22:04,572 autoreload 97942 4334994816 Watching for file changes with StatReloader
INFO 2022-05-08 15:22:15,862 basehttp 97942 6169915392 "POST /api/token/ HTTP/1.1" 200 483
INFO 2022-05-08 15:22:39,752 basehttp 97942 6169915392 "GET /project/ HTTP/1.1" 200 205
INFO 2022-05-08 15:24:10,788 basehttp 97942 6169915392 "POST /project/ HTTP/1.1" 200 103
INFO 2022-05-08 15:24:58,773 basehttp 97942 6169915392 "GET /project/ HTTP/1.1" 200 309
ERROR 2022-05-08 15:25:11,120 log 97942 6169915392 Internal Server Error: /project/3
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: ProjectView.get() got an unexpected keyword argument 'projectId'
ERROR 2022-05-08 15:25:11,120 basehttp 97942 6169915392 "GET /project/3 HTTP/1.1" 500 80865
WARNING 2022-05-08 15:25:15,743 log 97942 6169915392 Not Found: /project/3/
WARNING 2022-05-08 15:25:15,743 basehttp 97942 6169915392 "GET /project/3/ HTTP/1.1" 404 3442
ERROR 2022-05-08 15:25:27,486 log 97942 6169915392 Internal Server Error: /project/3
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 94, in put
    projectObj = self.get_object(projectId)
  File "/Users/rashussain/Desktop/Project/api/views.py", line 91, in get_object
    return Issue.objects.get(projectId=projectId)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
myApp.models.Issue.DoesNotExist: Issue matching query does not exist.
ERROR 2022-05-08 15:25:27,487 basehttp 97942 6169915392 "PUT /project/3 HTTP/1.1" 500 96623
WARNING 2022-05-08 15:25:33,332 log 97942 6169915392 Not Found: /project/3/
WARNING 2022-05-08 15:25:33,333 basehttp 97942 6169915392 "PUT /project/3/ HTTP/1.1" 404 3442
INFO 2022-05-08 15:26:14,689 autoreload 97942 4334994816 /Users/rashussain/Desktop/Project/api/views.py changed, reloading.
INFO 2022-05-08 15:26:14,972 autoreload 99233 4347413888 Watching for file changes with StatReloader
INFO 2022-05-08 15:26:26,745 basehttp 99233 6156169216 "PUT /project/3 HTTP/1.1" 200 103
INFO 2022-05-08 15:26:34,301 basehttp 99233 6156169216 "GET /project/ HTTP/1.1" 200 309
INFO 2022-05-08 15:26:44,146 basehttp 99233 6156169216 "DELETE /project/3 HTTP/1.1" 200 17
ERROR 2022-05-08 15:26:47,903 log 99233 6156169216 Internal Server Error: /project/3
Traceback (most recent call last):
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/rashussain/Library/Python/3.10/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: ProjectView.get() got an unexpected keyword argument 'projectId'
ERROR 2022-05-08 15:26:47,904 basehttp 99233 6156169216 "GET /project/3 HTTP/1.1" 500 80865
INFO 2022-05-08 15:26:51,845 basehttp 99233 6156169216 "GET /project/ HTTP/1.1" 200 205
INFO 2022-05-08 15:27:02,215 basehttp 99233 6156169216 "GET /admin/myApp/project/ HTTP/1.1" 200 7292
INFO 2022-05-08 15:27:02,261 basehttp 99233 6156169216 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2022-05-08 15:27:03,475 basehttp 99233 6156169216 "GET /admin/myApp/issue/ HTTP/1.1" 200 7288
INFO 2022-05-08 15:27:03,525 basehttp 99233 6156169216 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
